# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  panda_joint1: 0.0
  panda_joint2: -1.5
  panda_joint3: 0
  panda_joint4: -2
  panda_joint5: 0.0
  panda_joint6: 1.571
  panda_joint7: 0.785
